/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_asus1_ffmpeglearn_NDKTest */

#ifndef _Included_com_example_asus1_ffmpeglearn_NDKTest
#define _Included_com_example_asus1_ffmpeglearn_NDKTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_asus1_ffmpeglearn_NDKTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_asus1_ffmpeglearn_NDKTest_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
