/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_asus1_learnjniandndk_JNIUtil */

#ifndef _Included_com_example_asus1_learnjniandndk_JNIUtil
#define _Included_com_example_asus1_learnjniandndk_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_asus1_learnjniandndk_JNIUtil
 * Method:    getWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_asus1_learnjniandndk_JNIUtil_getWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
